### PR TITLE
Fix build with Qt >= 5.8.0

### PR DESCRIPTION
**Pull request by jelly**
platformsupport-private was modularized in Qt 5.8.
Use the appropriate theme_support-private module

### CODE REVIEW

**Comment by eli-schwartz** [comment]
That `load(qt_plugin)` removal thing was probably because keeping it there causes the build to error with:
```
####### Building headless QPA plugin #######
Info: creating stash file /home/eschwartz/git/calibre/build/headless/.qmake.stash
Project ERROR: Could not find feature reduce_exports.
Error while executing: /usr/bin/qmake-qt5 headless.pro
```

But when removing it, it errors anyway with:
```
g++ -pipe -O2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp
g++ -c -pipe -O2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_THEME_SUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/qt -isystem /usr/include/qt/QtThemeSupport -isystem /usr/include/qt/QtThemeSupport/5.8.0 -isystem /usr/include/qt/QtThemeSupport/5.8.0/QtThemeSupport -isystem /usr/include/qt/QtGui/5.8.0 -isystem /usr/include/qt/QtGui/5.8.0/QtGui -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore/5.8.0 -isystem /usr/include/qt/QtCore/5.8.0/QtCore -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o headless_backingstore.o /home/eschwartz/git/calibre/src/calibre/headless/headless_backingstore.cpp
g++ -c -pipe -O2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_THEME_SUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -isystem /usr/include/qt -isystem /usr/include/qt/QtThemeSupport -isystem /usr/include/qt/QtThemeSupport/5.8.0 -isystem /usr/include/qt/QtThemeSupport/5.8.0/QtThemeSupport -isystem /usr/include/qt/QtGui/5.8.0 -isystem /usr/include/qt/QtGui/5.8.0/QtGui -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore/5.8.0 -isystem /usr/include/qt/QtCore/5.8.0/QtCore -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o headless_integration.o /home/eschwartz/git/calibre/src/calibre/headless/headless_integration.cpp
In file included from /home/eschwartz/git/calibre/src/calibre/headless/headless_backingstore.cpp:2:0:
/home/eschwartz/git/calibre/src/calibre/headless/headless_integration.h:6:62: fatal error: QtPlatformSupport/private/qgenericunixservices_p.h: No such file or directory
 #include <QtPlatformSupport/private/qgenericunixservices_p.h>
                                                              ^
In file included from /home/eschwartz/git/calibre/src/calibre/headless/headless_integration.cpp:2:0:
/home/eschwartz/git/calibre/src/calibre/headless/headless_integration.h:6:62: fatal error: QtPlatformSupport/private/qgenericunixservices_p.h: No such file or directory
 #include <QtPlatformSupport/private/qgenericunixservices_p.h>
                                                              ^
compilation terminated.
```

So this still doesn't build on Qt 5.8 (currently in Arch Linux [testing] repo).
@jelly's additional patch in https://git.archlinux.org/svntogit/community.git/log/trunk/calibre-qt-5.8.patch?h=packages/calibre seems to work though, the build goes through at least.

**Comment by kovidgoyal** [comment]
load(qt_plugin) is needed for Qt < 5.8 it loads the qt_plugin.prf file which 

I dont know if it is needed for Qt 5.8 or not since the Qt build system changed a lot for 5.8. Unfortunately, I dont currently have the time to setup a Qt 5.8 env to work on this.

**Comment by jelly** [comment]
I will provide a patch which fixes the old and new situation tonight.

**Comment by kovidgoyal** [comment]
Cool. The headless plugin is tested by test_qt() in text_build.py which you can run as follows:

```
python setup.py test --test-name qt
```
